/* eslint-disable no-console */
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Banner from '../components/Home Page/MinBanner'
import AboutCompanySection from '../components/Home Page/ToColumn'
import ProjectsPreviewSection from '../components/Home Page/ProjectPreview'
import PartnerLogoSection from '../components/Home Page/PartnerLogo'
import ClientConnectionSection from '../components/Home Page/ClientConnection'
import CountersSection from '../components/Home Page/Counters'
import { aboutHomePage } from '../../public/json/data'
import { clientConnectionSectionData } from '../../public/json/data'
import { useCounterInfo } from '../framework/basic-react/auth/countersInfo'
import { useOurPartner } from '../framework/basic-react/auth/partnerData'
import { useourBanner } from '../framework/basic-react/auth/ourBanner'
import { home } from '../../utils/AppConfing'
import { Meta } from '../components/Meta'
import { useOurProject } from '../framework/basic-react/auth/ourProject'
import { useClientConnection } from '../framework/basic-react/auth/clientConnection'
import { useEffect, useState } from 'react'
import SiteEnvironmentSection from '../components/Home Page/SiteEnvironment'
import PartnersSection from '../components/Home Page/PartnersSection'
import CookiesPopup from '../cookies/CookiesPopup'

const HomePage = () => {
  const [saveImage, setSaveImage] = useState<any>([])
  const [saveData, setSaveData] = useState<any>()
  const [filter, setFilter] = useState(0)

  const { data: counterInfo } = useCounterInfo()
  const { data: ourPartner } = useOurPartner()
  const { data: ourBanner } = useourBanner()
  const { data, mutate: ourProjects } = useOurProject()
  const { data: clientfeedback } = useClientConnection()

  useEffect(() => {
    if (ourBanner && ourBanner != undefined) {
      setSaveImage(ourBanner)
    } else {
      setSaveImage([
        { image_path: '/tmp/1715949381080image-Rectangle%204.png' },
      ])
    }
  }, [ourBanner])

  useEffect(() => {
    if (data?.data?.data && data?.data?.data != undefined) {
      setSaveData(data?.data.data)
    } else {
      const value = data?.data.data
      setSaveData([{ value }])
    }
  }, [data?.data.data])

  useEffect(() => {
    ourProjects(filter)
  }, [filter, ourProjects])

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>H.K.Construction</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="space-y-16 lg:space-y-24">
          <Banner BannerData={saveImage} />
          <AboutCompanySection AboutData={aboutHomePage} />
          <SiteEnvironmentSection />
          <CountersSection Scroll={170} CounterData={counterInfo} />
          <ProjectsPreviewSection
            ProjectsPreviewData={saveData}
            filterValue={setFilter}
          />
          <ClientConnectionSection
            ClientConnection={clientConnectionSectionData}
            FeedBackData={clientfeedback}
          />
          <PartnerLogoSection PartnerLogoData={ourPartner} />
          <PartnersSection />
        </div>
      </div>
      <CookiesPopup />
      <Meta title={home?.title} description={home?.description} />
    </>
  )
}

export default HomePage
